// Package scheme provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package scheme

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Status.
const (
	Ok        Status = "ok"
	Unhealthy Status = "unhealthy"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status Status `json:"status"`
}

// NewTodo defines model for NewTodo.
type NewTodo struct {
	Title string `json:"title"`
}

// Status defines model for Status.
type Status string

// Todo defines model for Todo.
type Todo struct {
	Completed bool               `json:"completed"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
}

// UpdateTodo defines model for UpdateTodo.
type UpdateTodo struct {
	Completed *bool   `json:"completed,omitempty"`
	Title     *string `json:"title,omitempty"`
}

// PostTodosJSONRequestBody defines body for PostTodos for application/json ContentType.
type PostTodosJSONRequestBody = NewTodo

// PutTodosIdJSONRequestBody defines body for PutTodosId for application/json ContentType.
type PutTodosIdJSONRequestBody = UpdateTodo
